const { pickDose } = require("./newsletter-dose");
const { sendNewsletterEmail } = require("./mail");
const { sendPushToAll, pushPayloadFromDose } = require("./push");

function getSetting(db, key, fallback) {
  try {
    const row = db.prepare("SELECT value FROM newsletter_settings WHERE key = ?").get(key);
    return row ? row.value : fallback;
  } catch {
    return fallback;
  }
}

function setSetting(db, key, value) {
  const now = new Date().toISOString();
  db.prepare(
    `INSERT INTO newsletter_settings (key, value, updated_at) VALUES (?, ?, ?)
     ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`
  ).run(key, String(value), now);
}

function isAutoEnabled(db) {
  return getSetting(db, "auto_enabled", "1") !== "0";
}

function intervalMs(db) {
  const hours = parseFloat(getSetting(db, "interval_hours", process.env.NEWSLETTER_INTERVAL_HOURS || "24"));
  return Math.max(1, hours) * 60 * 60 * 1000;
}

function lastSentAt(db) {
  const row = db
    .prepare(
      `SELECT COALESCE(sent_at, created_at) AS t FROM newsletters ORDER BY COALESCE(sent_at, created_at) DESC LIMIT 1`
    )
    .get();
  return row?.t || null;
}

function shouldSendNow(db) {
  if (!isAutoEnabled(db)) return false;
  const last = lastSentAt(db);
  if (!last) return true;
  const elapsed = Date.now() - new Date(last).getTime();
  return elapsed >= intervalMs(db);
}

async function publishDose(db, { createdBy = null, autoGenerated = 0, dose = null } = {}) {
  const picked = dose || pickDose(db);
  if (!picked) {
    return { ok: false, error: "لا يوجد محتوى كافٍ في المساعد أو المكتبة." };
  }

  const now = new Date().toISOString();
  const r = db
    .prepare(
      `INSERT INTO newsletters (subject, content, created_by, sent_at, created_at, source_type, source_ref, link_url, auto_generated)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    )
    .run(
      picked.subject,
      picked.content,
      createdBy,
      now,
      now,
      picked.source_type,
      picked.source_ref,
      picked.link_url,
      autoGenerated ? 1 : 0
    );

  const saved = {
    id: r.lastInsertRowid,
    ...picked,
    sent_at: now,
  };

  const members = db
    .prepare(
      `SELECT id, email, full_name FROM users
       WHERE status = 'active' AND role IN ('member','cadre','supervisor','admin','designer')`
    )
    .all();

  let emailsOk = 0;
  for (const u of members) {
    if (!u.email || u.email.endsWith("@shifra.local")) continue;
    const entry = await sendNewsletterEmail(u, saved, db);
    if (entry.status === "sent" || entry.status === "console") emailsOk += 1;
  }

  const push = await sendPushToAll(db, pushPayloadFromDose(saved));

  return {
    ok: true,
    dose: saved,
    memberCount: members.length,
    emailsOk,
    push,
  };
}

module.exports = {
  publishDose,
  shouldSendNow,
  isAutoEnabled,
  intervalMs,
  lastSentAt,
  getSetting,
  setSetting,
};
